# Generated by Django 5.0.6 on 2025-03-21 09:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_location_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profiles/user-default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
